// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VerzamelingFinished;

#nullable disable

namespace VerzamelingFinished.Migrations
{
    [DbContext(typeof(DBcontext))]
<<<<<<<< HEAD:VerzamelingFinished/Migrations/20241003155958_AddDeckTable.Designer.cs
    [Migration("20241003155958_AddDeckTable")]
    partial class AddDeckTable
========
    [Migration("20240930115703_addpokemon")]
    partial class addpokemon
>>>>>>>> API:VerzamelingFinished/Migrations/20240930115703_addpokemon.Designer.cs
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0-rc.1.24451.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("VerzamelingFinished.Models.Card", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("DeckId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Element")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Image")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Price")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DeckId");

                    b.ToTable("Cards", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "An electric-type Pokémon",
                            Element = "Electric",
                            Image = "test",
                            Name = "Pikachu",
                            Price = 10,
                            Quantity = 1
                        });
                });

            modelBuilder.Entity("VerzamelingFinished.Models.Deck", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CardCount")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Decks", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CardCount = 0,
                            Description = "This is a sample deck",
                            Image = "sample.jpg",
                            Name = "Sample Deck"
                        });
                });

            modelBuilder.Entity("VerzamelingFinished.Models.Card", b =>
                {
                    b.HasOne("VerzamelingFinished.Models.Deck", "Deck")
                        .WithMany("Cards")
                        .HasForeignKey("DeckId")
                        .HasConstraintName("FK_Cards_Deck");

                    b.Navigation("Deck");
                });

            modelBuilder.Entity("VerzamelingFinished.Models.Deck", b =>
                {
                    b.Navigation("Cards");
                });
#pragma warning restore 612, 618
        }
    }
}
